import { SignIn } from "@clerk/nextjs";

export const metadata = {
  title: "demoClerk - Sign In",
  description: "Generated by create next app",
};


    export default function Page(){

        return <SignIn/>

    }