import React from 'react'
import Image from 'next/image'
import Link from 'next/link';


export const metadata = {
  title: "demoClerk - About",
  description: "Generated by create next app",
};


export default function About() {
  return (
 

    <>

<section className="promo-section">
  <div className="promo-container">
    <div className="promo-grid">
      
      <div className="promo-text-box">
        <div className="promo-text-content">
          <h2 className="promo-heading">
          Discover Our Premium Collection
          </h2>

          <p className="promo-paragraph">
           Explore our exclusive range of footwear and apparel designed for ultimate comfort and style. 
            Whether you’re hitting the track or the streets, our products blend cutting-edge technology 
            with timeless designs to elevate your everyday performance.
          </p>

          <div className="promo-button-wrapper">
            <Link href="/contact" className="promo-button">
              Get Started Today 
            </Link>
          </div>
        </div>
      </div>

      <div className="promo-images-grid">
        <Image
          width={300}
          height={500}
          alt="Product 1"
          src="https://images.unsplash.com/photo-1621274790572-7c32596bc67f?ixlib=rb-1.2.1&auto=format&fit=crop&w=654&q=80"
          className="promo-image"
        />
        <Image
          width={350}
          height={500}
          alt="Product 2"
          src="https://images.unsplash.com/photo-1567168544813-cc03465b4fa8?ixlib=rb-1.2.1&auto=format&fit=crop&w=774&q=80"
          className="promo-image"
        />
      </div>

    </div>
  </div>
</section>


    </>
  )
}
