import Header from "@/Components/Home/Header";
import Section from "@/Components/Home/Section";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider , ClerkLoaded , ClerkLoading  } from "@clerk/nextjs";
import Loader from "@/Components/Home/Loader";





const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "demoClerk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <ClerkProvider >
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <ClerkLoading>
     <Loader/>
      </ClerkLoading>
      <ClerkLoaded>
      <Header/>
        {children}
        <Section/>
      </ClerkLoaded>
      </body>
    </html>
    </ClerkProvider>
  );
}
