import React from 'react'



export const metadata = {
  title: "demoClerk - Sanity",
  description: "Generated by create next app",
};

export default function Sanity() {
  return (
    <div>Sanity</div>
  )
}
